
services:
  geth:
    # Image with pre-loaded contracts
    # image: geth-contracts:0.0.1

    # Basic all-tools image
    # image: go-etherium:0.0.1-all-tools
    image: ghcr.io/m0sh1x2/go-ethereum-alltools:master

    # --http # works in localhost but doesn't listen on the public address
    command:  >
      geth
      --dev 
      --http
      --http.addr 0.0.0.0 
      --http.api eth,web3,debug,net 
      --http.corsdomain "https://remix.ethereum.org"
      --datadir=/root/.ethereum
      --http.vhosts="*"
      --allow-insecure-unlock 

    # For debug purposes:
    # command:  sleep 3000
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    healthcheck:
      test: ["CMD", "geth", "--exec", "net.listening", "attach", "http://localhost:8545"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s
#     volumes:
#       - geth-datadir:/root/.ethereum

# volumes:
#   geth-datadir:

