# Support setting various labels on the final image
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

# We directly use the alltools image and then load the contracts into the new one - to save build time
FROM ghcr.io/m0sh1x2/go-ethereum-alltools:master

# Set up the devnet checkpoint
# IMPORTANT: If the directory is overwritten then the contracts and state will be gone.
COPY ./deploy/checkpoint/checkpoint.tar.gz .
RUN mkdir /root/.ethereum && tar xfz checkpoint.tar.gz -C /root/.ethereum && rm checkpoint.tar.gz

EXPOSE 8545 8546 30303 30303/udp

# Add some metadata labels to help programmatic image consumption
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

LABEL commit="$COMMIT" version="$VERSION" buildnum="$BUILDNUM"
