# Support setting various labels on the final image
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

# Build Geth in a stock Go builder container
FROM golang:1.26-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers git

# Get dependencies - will also be cached if we won't change go.mod/go.sum
COPY go.mod /go-ethereum/
COPY go.sum /go-ethereum/
RUN cd /go-ethereum && go mod download

ADD . /go-ethereum
RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/geth

# Pull Geth into a second stage deploy alpine container
# FROM alpine:latest

# RUN apk add --no-cache ca-certificates
# COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

FROM node:24

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

# This doesn't work as expected, the layer stays running forever
RUN geth \
  --dev \
  --http \
  --http.addr 0.0.0.0 \
  --http.api eth,web3,debug,net \
  --http.corsdomain "https://remix.ethereum.org" \
  --datadir=/root/.ethereum \
  --http.vhosts="*" \
  --allow-insecure-unlock

RUN npx hardhat run hardhat/scripts/deploy-counter.ts --build-profile production --network geth


EXPOSE 8545 8546 30303 30303/udp
ENTRYPOINT ["geth"]

# Add some metadata labels to help programmatic image consumption
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

LABEL commit="$COMMIT" version="$VERSION" buildnum="$BUILDNUM"
