name: Smart Contract Image Build
run-name: ${{ github.actor }} building smart contract geth image
on: 
  push:
    branches:
      - test-branch
  pull_request:
    # types: [closed] # trigger only on closed pull reqeusts
    branches:
      - test-branch
  workflow_dispatch: # allow manual rebuilds

# Docs/Guide provides info that ghcr is supported out of the box with the docker actions + recommend usage of action sha.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-contracts

jobs:
  Build-Contract-Container-Image:
    runs-on: ubuntu-latest

    # if: >
    #   github.event.pull_request.merged == true &&
    #   contains(github.event.pull_request.labels.*.name, 'CI:Deploy')

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # 1. Add Buildx - Required for Docker caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Here we run the contract workflow, we should exit 1 when successsfully completed.
      # TODO: Do we use --wait-on-container exit or it should work as expected in Github Actions?
      - name: Run Compose and devnet contract bind state
        run: docker compose -f docker-compose.contracts.yml up

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # This should be generated by the docker-compose + use the same directory as the image build step
      - name: Verify existance of extracted contracts and devnet export 
        run: ls -lat deploy/checkpoint

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          file: ./deploy/Dockerfile.contracts
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 2. Add Caching configuration
          cache-from: type=gha,scope=${{ github.workflow }}-${{ env.IMAGE_NAME }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ env.IMAGE_NAME }}


      # We can set env variables in a strange way with GitHub Actions: https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions
      - name: Set Geth Image Env
        run: |
          # Convert everything to lowercase using bash parameter expansion - asked Gemini for help
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_LOWER=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
          
          echo "GETH_IMAGE=ghcr.io/${REPO_LOWER}-contracts:${TAG_LOWER}" >> $GITHUB_ENV

      - name: Run Compose Test
        run: docker compose -f docker-compose.tests.yml up --abort-on-container-exit

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
